// strings should be unique across reducers so namespace them with the reducer name

export const CHESSBOARD_FENCHANGED = 'chessboard.CHESSBOARD_FENCHANGED';
export const CHESSBOARD_FLIPBOARD = 'chessboard.CHESSBOARD_FLIPBOARD';
export const CHESSBOARD_LIGHTSQUARECOLORCHANGED = 'chessboard.CHESSBOARD_LIGHTSQUARECOLORCHANGED';
export const CHESSBOARD_DARKSQUARECOLORCHANGED = 'chessboard.CHESSBOARD_DARKSQUARECOLORCHANGED';
export const CHESSBOARD_LASTMESSAGE = 'chessboard.CHESSBOARD_LASTMESSAGE';
export const CHESSBOARD_FILECHANGED = 'chessboard.CHESSBOARD_FILECHANGED';
export const CHESSBOARD_RANKCHANGED = 'chessboard.CHESSBOARD_RANKCHANGED';
export const CHESSBOARD_GAMETYPECHANGED = 'chessboard.CHESSBOARD_GAMETYPECHANGED';
export const CHESSBOARD_PGNCHANGED = 'chessboard.CHESSBOARD_PGNCHANGED';
